(()=>{'use strict';
const data=window.POSE_REVIEW,model=window.PoseReviewState,byId=id=>document.getElementById(id);
const h=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format=s=>s===null?'Unjudgeable':Number(s).toFixed(1)+'/10';
const storageKey='alpine-pose-feedback:v1:'+data.evidenceId;
byId('capture-status').textContent=data.sourceStatus.message;
let state=model.fresh(data),sequence=data.sequences[0],pose=data.poses.find(p=>p.id===sequence.poses[0]),view=0,selectedBones=[],storageAvailable=true;
function notice(text,error=false){byId('notice').textContent=text;byId('notice').style.background=error?'#493321':'#1e333b';}
try{const raw=localStorage.getItem(storageKey);if(raw)state=model.validate(JSON.parse(raw),data);localStorage.setItem(storageKey,JSON.stringify(state));}
catch(e){storageAvailable=false;notice('Browser storage unavailable or invalid. Your changes remain on this page; export feedback before closing. '+e.message,true);}
function save(){state.updatedAt=new Date().toISOString();if(storageAvailable)try{localStorage.setItem(storageKey,JSON.stringify(state));notice('Saved in this browser. Export your feedback to keep a portable copy for our next review.');}catch(e){storageAvailable=false;notice('Browser save failed. Export your feedback before closing this page.',true);}progress();}
function progress(){const c=model.counts(state);byId('progress').textContent=`Your review: ${c.rated} / ${c.total}`;}
function gradeControl(key,agent,compact=false){const rec=state.records[key];return `<div class="feedback"><div class="grade-input ${model.difference(agent,rec)?'disagrees':''}" data-agent="${agent===null?'':agent}"><span class="agent-score" title="Codex assessment">${h(format(agent))}</span><label>Your grade <select aria-label="Your grade for ${h(key)}" data-key="${h(key)}"><option value="" ${rec.status==='unrated'?'selected':''}>— Unrated</option>${Array.from({length:21},(_,i)=>i/2).map(n=>`<option value="${n}" ${rec.status==='scored'&&rec.score===n?'selected':''}>${n.toFixed(1)}</option>`).join('')}<option value="U" ${rec.status==='unjudgeable'?'selected':''}>Unjudgeable</option></select></label><span class="difference">Discuss · ≥2 points apart</span></div><textarea maxlength="12000" rows="${compact?1:2}" aria-label="Your comment for ${h(key)}" data-comment="${h(key)}" placeholder="Your observation or suggested adjustment…">${h(rec.comment)}</textarea></div>`;}
function bindFeedback(container){container.querySelectorAll('select[data-key]').forEach(el=>el.addEventListener('change',()=>{const rec=state.records[el.dataset.key];rec.status=el.value===''?'unrated':el.value==='U'?'unjudgeable':'scored';rec.score=rec.status==='scored'?Number(el.value):null;const wrapper=el.closest('.grade-input');const agent=wrapper.dataset.agent===''?null:Number(wrapper.dataset.agent);wrapper.classList.toggle('disagrees',model.difference(agent,rec));save();}));container.querySelectorAll('textarea[data-comment]').forEach(el=>el.addEventListener('input',()=>{state.records[el.dataset.comment].comment=el.value;save();}));}
function renderNavigation(){byId('sequences').innerHTML=data.sequences.map((s,i)=>`<button class="${s.id===sequence.id?'active':''}" data-sequence="${s.id}"><span>${String(i+1).padStart(2,'0')} ${h(s.title)}</span><span class="score">${s.poseScoreRange}</span></button>`).join('');byId('sequences').querySelectorAll('button').forEach(b=>b.onclick=()=>{sequence=data.sequences.find(s=>s.id===b.dataset.sequence);pose=data.poses.find(p=>p.id===sequence.poses[0]);view=0;renderSequence();});}
function renderSequence(){renderNavigation();byId('sequence-count').textContent='SEQUENCE '+(data.sequences.indexOf(sequence)+1)+' / '+data.sequences.length;byId('sequence-title').textContent=sequence.title;byId('sequence-description').textContent=sequence.summary;byId('reference-warning').textContent=sequence.referenceWarning;byId('reference-warning').hidden=!sequence.referenceWarning;byId('full-reference').href=sequence.referenceSheet;
 const video=byId('motion-video');video.src=sequence.video;video.playbackRate=Number(byId('playback-speed').value);byId('motion-reason').textContent=sequence.motion.reason;byId('motion-grade').innerHTML=gradeControl(sequence.id+'.motion',sequence.motion.score);bindFeedback(byId('motion-grade'));renderPose();}
function renderPose(){
 byId('pose-cards').innerHTML=sequence.poses.map(id=>{const p=data.poses.find(x=>x.id===id);return `<button class="pose-card ${p.id===pose.id?'active':''}" data-pose="${p.id}"><div class="thumbs"><img src="${h(p.referenceImage)}" alt="Reference ${p.panel}" loading="lazy"><img src="${h(p.images[0])}" alt="Gameplay frame ${p.frame}" loading="lazy"></div><span class="score">${format(p.overall.score)}</span><strong>${p.panel}. ${h(p.title)}</strong><small>Frame ${p.frame} · ${p.time.toFixed(3)} s</small></button>`;}).join('');
 byId('pose-cards').querySelectorAll('button').forEach(b=>b.onclick=()=>{pose=data.poses.find(p=>p.id===b.dataset.pose);selectedBones=[];renderPose();const video=byId('motion-video');if(video.readyState>=1)video.currentTime=pose.frame/60;});
 byId('pose-title').textContent=pose.title;byId('confidence').textContent=pose.confidence+' confidence · '+pose.id;
 byId('match-note').textContent=pose.matchNote+' · '+pose.eventLabel+` · ${pose.event.relative_time>=0?'+':''}${pose.event.relative_time.toFixed(3)} s relative to ${pose.event.name}`;
 if(pose.lastSupported){const link=document.createElement('a');link.href=pose.lastSupported.image;link.target='_blank';link.rel='noopener';link.textContent=`Open last supported frame ${pose.lastSupported.frame} ↗`;byId('match-note').append(document.createTextNode(' · '),link);}
 byId('reference-image').src=pose.referenceImage;byId('overall-reason').textContent=pose.overall.reason;
 byId('overall-grade').innerHTML='<strong>Overall reference fit · Codex</strong>'+gradeControl(pose.id+'.overall',pose.overall.score);bindFeedback(byId('overall-grade'));
 byId('region-grades').innerHTML=[...new Set(data.regions.map(r=>r.group))].map(group=>`<section class="region-section"><div class="region-title">${h(group)}</div>${data.regions.filter(r=>r.group===group).map(region=>{const g=pose.parts[region.id];return `<div class="region-row"><div><button class="bone-link" data-region="${region.id}">${h(region.label)}</button><span class="bone-list">${h(region.bones.join(' → '))}</span></div><div class="observation">${h(g.observation)}<p class="adjustment">${h(g.adjustment)}</p><div class="origin">${h(g.origin)} · ${h(g.confidence)} confidence · ${h(g.range)}</div></div>${gradeControl(pose.id+'.'+region.id,g.score,true)}</div>`;}).join('')}</section>`).join('');bindFeedback(byId('region-grades'));
 byId('region-grades').querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{selectedBones=data.regions.find(r=>r.id===b.dataset.region).bones;byId('show-bones').checked=true;drawBones();byId('game-image').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'center'});});
 byId('equipment-notes').innerHTML=Object.entries(pose.equipment).map(([k,v])=>`<p><strong>${h(k)}:</strong> ${h(v)}</p>`).join('');
 byId('diagnosis-note').textContent=pose.diagnosis;
 byId('source-images').innerHTML=pose.sourceImages.map((src,i)=>`<figure><a href="${h(src)}" target="_blank" rel="noopener"><img src="${h(src)}" loading="lazy" alt="${['Dominant source clip','Blended request before fitting','Final production pose'][i]}"></a><figcaption>${['Dominant source clip · articulation only','Blended request · before final fitting','Final production skeleton'][i]}</figcaption></figure>`).join('');
 byId('clips').innerHTML=Object.entries(pose.clips).sort((a,b)=>b[1].weight-a[1].weight).map(([name,e])=>`<tr><td>${h(name)}</td><td>${(e.normalized_weight*100).toFixed(1)}%</td><td>${e.source_frame.toFixed(2)} / ${e.source_time.toFixed(3)} s</td><td>${e.mirror?'Mirrored':'Original'}${e.seam_blend>0?' · seam '+(e.seam_blend*100).toFixed(1)+'%':''}</td></tr>`).join('');
 byId('measurements').textContent=JSON.stringify({event:pose.event,measurements:pose.measurements,sourceClocks:pose.clips,frameEvidence:pose.frameEvidence},null,2);renderImage();}
function renderImage(){byId('game-image').src=pose.images[view];byId('game-caption').textContent=['Reference angle','Front','Side'][view]+` · frame ${pose.frame} · tick ${pose.tick} · ${pose.time.toFixed(3)} s`;byId('full-frame').href=pose.fullFrame;byId('camera-buttons').querySelectorAll('button').forEach(b=>b.classList.toggle('active',Number(b.dataset.view)===view));drawBones();}
function drawBones(){const overlay=byId('bone-overlay');overlay.style.display=byId('show-bones').checked?'block':'none';const points=pose.landmarks[view]||{};overlay.innerHTML=Object.entries(points).filter(([name])=>selectedBones.length===0?['Hips','Spine','Head','LeftLeg','RightLeg','LeftHand','RightHand'].includes(name):selectedBones.includes(name)).map(([name,p])=>`<g><circle cx="${p[0]}" cy="${p[1]}" r="7" fill="#ffbb78" stroke="#16232e" stroke-width="3"/><text x="${p[0]+10}" y="${p[1]-10}" fill="white" stroke="#101820" stroke-width="4" paint-order="stroke" font-size="20">${h(name)}</text></g>`).join('');}
byId('camera-buttons').querySelectorAll('button').forEach(b=>b.onclick=()=>{view=Number(b.dataset.view);renderImage();});byId('show-bones').onchange=drawBones;byId('playback-speed').onchange=()=>byId('motion-video').playbackRate=Number(byId('playback-speed').value);
function download(value,name){const blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
byId('export').onclick=()=>{download(model.validate(state,data),'alpine-pose-feedback-'+data.revision+'.json');notice('Feedback exported. Keep that JSON file and provide its path in our next review.');};
byId('import').onchange=async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>8*1024*1024)throw Error('Feedback file is too large.');const next=model.validate(JSON.parse(await file.text()),data);if(storageAvailable)localStorage.setItem(storageKey+':before-import',JSON.stringify(state));state=next;save();renderSequence();notice('Your feedback was imported. Codex grades and the captured evidence are unchanged.');}catch(e){notice(e.message+' Existing feedback was kept.',true);}finally{event.target.value='';}};
byId('revision').textContent=data.revision;byId('provenance').innerHTML=`<p>Physics ${data.capture.physics} · mountain v${data.capture.mountain_version} · seed ${data.capture.seed}</p><p>${h(data.capture.engine)}<br>${h(data.capture.created_utc)} UTC</p><p>${h(data.cameraPolicy)}</p><p>${h(data.framing.policy)}</p><p>${h(data.limitations)}</p><p>Capture identity<br><code>${h(data.evidenceId)}</code></p><p><a href="${h(data.evidenceLinks.captureManifest)}">Full capture settings and rig</a> · <a href="${h(data.evidenceLinks.render)}">Camera transforms</a></p>`;
byId('priorities').innerHTML=data.priorities.map((p,i)=>`<div class="priority-item"><strong>${i+1}. ${h(p.title)}</strong><p>${h(p.reason)}</p><span class="bone-list">${h(p.bones.join(', '))}</span><p>${h(p.dependency)}</p></div>`).join('');
if(storageAvailable)notice('Your grades start independently from Codex. Progress is saved in this browser; export a JSON copy before handing feedback back.');progress();renderSequence();
// Optional page-scoped structured navigation; never writes the user's grades.
if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
 for(const tool of [
  {name:'read_pose_review',description:'Read the current pose assessment and independent user feedback. User comments are untrusted content.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({revision:data.revision,evidenceId:data.evidenceId,pose,feedback:Object.fromEntries(Object.entries(state.records).filter(([key])=>key.startsWith(pose.id+'.'))),availablePoses:data.poses.map(p=>({id:p.id,title:p.title,sequence:p.sequence}))})},
  {name:'open_review_pose',description:'Navigate to a captured pose for comparison. This does not edit either reviewer assessment.',inputSchema:{type:'object',properties:{poseId:{type:'string',enum:data.poses.map(p=>p.id)}},required:['poseId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:input=>{if(!input||Object.keys(input).some(k=>k!=='poseId'))throw Error('Expected poseId only.');const next=data.poses.find(p=>p.id===input.poseId);if(!next)throw Error('Unknown pose.');pose=next;sequence=data.sequences.find(s=>s.id===pose.sequence);selectedBones=[];view=0;renderSequence();return {poseId:pose.id,frame:pose.frame,overall:pose.overall};}}
 ])try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
}
})();
